### ISSUE TITLE
segfault due to bad (?) compilation on rhel 8

### ISSUE THREAD

**Issue by wiad** [ARPA-SIMC/cdo-rpm#1]
Under certain circumstances, running cdo built via this spec file on rhel 8 segfaults with following error:
```
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = char*; _Alloc = std::allocator<char*>; std::vector<_Tp, _Alloc>::reference = char*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```
(this is reported by one of my users who understands cdo and netcdf, i will follow up later with a description of how to reproduce this error)

I have tested building cdo with the spec file that is provided in the cdo tar archive and that works. The difference is that the spec file in this project uses rpm built-in macros for` %configure` while the spec file from the cdo project uses regular `./configure`. Using the `%configure` macro results in that some default compilation flags are used when building the source code. Googling the segfault error message there are quite a few similar problems a few years back when the `GLIBCXX_ASSERTIONS` flag was added to the defaults in rpm's build macros. Looking at the build logs this flag is present when building with the spec file from this project but not when building with the cdo projects spec file, so I'm guessing that it is this gcc flag that is causing the problem. 

I'm not really familiar with gcc flags and debugging so I don't know really what needs to be done to 'fix' this other than not using the %configure macro. Maybe the problem should be fixed in the cdo project somehow and not here? But as it stands right now there are certain operations in a cdo binary provided through this spec file that can't be done.

**Comment by wiad** [comment]
More details about the problem and how to reproduce:

CDO crashes when executing mean operations, e.g. day, month or year mean. Here is an example reproducing the crash:
```
$ wget ftp://ftp.cdc.noaa.gov/Datasets/cpc_global_precip/precip.2019.nc
$ cdo daymean precip.2019.nc precip.2019_daymean.nc
$ cdo monmean precip.2019.nc precip.2019_monmean.nc
$ cdo yearmean precip.2019.nc precip.2019_yearmean.nc
```

Using the cdo build from the spec file in this project the above operations segfaults. By just changing `%configure` to `./configure` in the spec file the operations work as expected.

**Comment by pat1** [comment]
replicated the problem on Fedora 31
```
[root@localhost tmp]# cdo daymean precip.2019.nc precip.2019_daymean.nc
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = char*; _Alloc = std::allocator<char*>; std::vector<_Tp, _Alloc>::reference = char*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Annullato (core dump creato)
[root@localhost tmp]# cdo monmean precip.2019.nc precip.2019_monmean.nc
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = char*; _Alloc = std::allocator<char*>; std::vector<_Tp, _Alloc>::reference = char*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Annullato (core dump creato)
[root@localhost tmp]# cdo yearmean precip.2019.nc precip.2019_yearmean.nc
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = char*; _Alloc = std::allocator<char*>; std::vector<_Tp, _Alloc>::reference = char*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Annullato (core dump creato)
[root@localhost tmp]# rpm -qi cdo
Name        : cdo
Version     : 1.9.5
Release     : 1
Architecture: x86_64
Install Date: ven 24 apr 2020, 08:46:44
```

solved rebuilding the package with cdo 1.9.8

```
[pat1@localhost tmp]$ cdo daymean precip.2019.nc precip.2019_daymean.nc
cdo    daymean: Processed 1 variable over 729 timesteps [2.31s 42MB].
[pat1@localhost tmp]$ cdo monmean precip.2019.nc precip.2019_monmean.nc
cdo    monmean: Processed 1 variable over 376 timesteps [1.57s 41MB].
[pat1@localhost tmp]$ cdo yearmean precip.2019.nc precip.2019_yearmean.nc
cdo    yearmean: Processed 1 variable over 365 timesteps [1.48s 36MB].
```

 rpm -q cdo
cdo-1.9.8-1.x86_64

compiled on Fedora 31 as:
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DgFortran -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -pthread
```

**Comment by brancomat** [comment]
Thank you both for the thorough bug report and the example file.

As suggested by @pat1 I updgraded the package to last upstream version (1.9.8) keeping the `%configure` macro in the specfile and it seems to work fine (tested on epel8):
```
[dbranchini@otto]$ cdo daymean precip.2019.nc precip.2019_daymean.nc
cdo    daymean: Processed 1 variable over 729 timesteps [3.63s 41MB].
[dbranchini@otto]$ cdo monmean precip.2019.nc precip.2019_monmean.nc
cdo    monmean: Processed 1 variable over 376 timesteps [2.77s 40MB].
[dbranchini@otto]$  cdo yearmean precip.2019.nc precip.2019_yearmean.nc
cdo    yearmean: Processed 1 variable over 365 timesteps [2.73s 35MB].
```

The current specfile should fix the issue.
FYI if you're intrested in precompiled binaries this package is available in simc/stable copr repo: https://copr.fedorainfracloud.org/coprs/simc/stable/.

**Comment by wiad** [comment]
Thank you, that was really fast work! And yes, I was hoping I could use the package from the copr repo, I have tested it and it works.
