### ISSUE TITLE
copr repo for EPEL9

### ISSUE THREAD

**Issue by wiad** [ARPA-SIMC/cdo-rpm#2]
Is it possible to build cdo for RHEL9 and push it to a copr repo?

**Comment by brancomat** [comment]
Hi,
we're waiting a stable release of Rocky Linux 9 before starting a mass rebuild of the packages we're using.
However I tried to launch a quick build of cdo on a copr test repository:
https://copr.fedorainfracloud.org/coprs/simc/test/build/4554247/

Unfortunately netcdf-cxx-devel is not yet available in epel 9 repository:
https://src.fedoraproject.org/rpms/netcdf-cxx

I'll keep the issue open until we do a mass rebuild but it will take a while.

**Comment by wiad** [comment]
Hi, 
just checking in to see current status on this. netcdf-cxx seems to be pushed to epel9 now.

**Comment by brancomat** [comment]
Hi, we're still lagging behind with the mass rebuild for Rocky Linux 9 but I tried again a test build for cdo in our test repository and it worked:
https://download.copr.fedorainfracloud.org/results/simc/test/epel-9-x86_64/04812164-cdo/

Please note that this specific build is untested, provided "as is", without warranty, yadda yadda.

Files are also available via https://copr.fedorainfracloud.org/coprs/simc/test/ but `simc/test` copr repo could and will likely contain other obsolete/broken/untested packages.

I'll keep the issue open we'll have the package available in our stable repo for epel9.

**Comment by wiad** [comment]
I believe this package is built against wrong versions of hdf5 and netcdf:
```
  - nothing provides libhdf5.so.103()(64bit) needed by cdo-1.9.8-1.x86_64
  - nothing provides libnetcdf.so.15()(64bit) needed by cdo-1.9.8-1.x86_64
```
Those are the versions that are included in the rhel8 builds of hdf5 and netcdf, in rhel9 it should be
```
libhdf5.so.200()(64bit)
libnetcdf.so.19()(64bit)
```

**Comment by wiad** [comment]
I'm sorry, I was mistakenly testing against the wrong repo. The rhel9 build of cdo works fine to install!

**Comment by edigiacomo** [comment]
cdo for RHEL9 is available in our Copr repository https://copr.fedorainfracloud.org/coprs/simc/stable
